name: spectranet
channels:
  - anaconda
  - pytorch
  - bioconda
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - numpy=1.15.2=py37h6a91979_1
  - openssl=1.0.2p=h1de35cc_0
  - scipy=1.1.0=py37h28f7352_1
  - libffi=3.2.1=1
  - blas=1.0=mkl
  - cffi=1.11.5=py37h6174b99_1
  - click=7.0=py37_0
  - flask=1.0.2=py37_1
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.0=118
  - itsdangerous=0.24=py37_1
  - jinja2=2.10=py37_0
  - jpeg=9b=he5867d9_2
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.35=ha441bb4_0
  - libtiff=4.0.9=hcb84e12_2
  - markupsafe=1.0=py37h1de35cc_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py37hb8a8100_0
  - mkl_random=1.0.1=py37h5d10147_1
  - ncurses=6.1=h0a44026_0
  - ninja=1.8.2=py37h04f5b5a_1
  - numpy-base=1.15.2=py37h8a80b8c_1
  - olefile=0.46=py37_0
  - pillow=5.3.0=py37hb68e598_0
  - pip=10.0.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.0=hc167b69_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.4.3=py37_0
  - six=1.11.0=py37_1
  - sqlite=3.25.2=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - werkzeug=0.14.1=py37_0
  - wheel=0.32.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
  - pytorch=0.4.1=py37_cuda0.0_cudnn0.0_1
  - torchvision=0.2.1=py37_1
  - pip:
    - torch==0.4.1
prefix: /Users/Christa.Caggiano/miniconda3/envs/spectranet

